/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package memorymatchgame;

import java.awt.Color;

/**
 *
 * @author PC
 */

public class jeuxFrame extends javax.swing.JFrame {

    /**
     * Creates new form jeuxFrame
     */
    int i = 0;
    String t1[] = {"c" , "c"};
    String t2[] = {"c" , "c"};
    //fdf
    String t3[] = {"c" , "c"};
    public jeuxFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carte1 = new javax.swing.JLabel();
        carte2 = new javax.swing.JLabel();
        carte3 = new javax.swing.JLabel();
        carte4 = new javax.swing.JLabel();
        carte5 = new javax.swing.JLabel();
        carte6 = new javax.swing.JLabel();
        carte7 = new javax.swing.JLabel();
        carte8 = new javax.swing.JLabel();
        carte9 = new javax.swing.JLabel();
        carte10 = new javax.swing.JLabel();
        carte11 = new javax.swing.JLabel();
        carte12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        carte1.setBackground(new java.awt.Color(255, 0, 0));
        carte1.setOpaque(true);
        carte1.setPreferredSize(new java.awt.Dimension(50, 50));
        carte1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carte1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                carte1MousePressed(evt);
            }
        });

        carte2.setBackground(new java.awt.Color(51, 255, 204));
        carte2.setOpaque(true);
        carte2.setPreferredSize(new java.awt.Dimension(50, 50));

        carte3.setBackground(new java.awt.Color(0, 255, 0));
        carte3.setOpaque(true);
        carte3.setPreferredSize(new java.awt.Dimension(50, 50));
        carte3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carte3MouseClicked(evt);
            }
        });

        carte4.setBackground(new java.awt.Color(0, 51, 255));
        carte4.setOpaque(true);
        carte4.setPreferredSize(new java.awt.Dimension(50, 50));

        carte5.setBackground(new java.awt.Color(255, 0, 255));
        carte5.setOpaque(true);
        carte5.setPreferredSize(new java.awt.Dimension(50, 50));

        carte6.setBackground(new java.awt.Color(51, 255, 204));
        carte6.setOpaque(true);
        carte6.setPreferredSize(new java.awt.Dimension(50, 50));

        carte7.setBackground(new java.awt.Color(255, 255, 0));
        carte7.setOpaque(true);
        carte7.setPreferredSize(new java.awt.Dimension(50, 50));

        carte8.setBackground(new java.awt.Color(255, 255, 0));
        carte8.setOpaque(true);
        carte8.setPreferredSize(new java.awt.Dimension(50, 50));

        carte9.setBackground(new java.awt.Color(0, 255, 0));
        carte9.setOpaque(true);
        carte9.setPreferredSize(new java.awt.Dimension(50, 50));
        carte9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carte9MouseClicked(evt);
            }
        });

        carte10.setBackground(new java.awt.Color(255, 0, 255));
        carte10.setOpaque(true);
        carte10.setPreferredSize(new java.awt.Dimension(50, 50));

        carte11.setBackground(new java.awt.Color(0, 51, 255));
        carte11.setOpaque(true);
        carte11.setPreferredSize(new java.awt.Dimension(50, 50));

        carte12.setBackground(new java.awt.Color(255, 0, 0));
        carte12.setOpaque(true);
        carte12.setPreferredSize(new java.awt.Dimension(50, 50));
        carte12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carte12MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 255, 204));
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(carte9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carte5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(carte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carte6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carte10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(carte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(carte7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(carte11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carte8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carte4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carte12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carte4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carte5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carte6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carte7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carte8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carte9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carte10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carte11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carte12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carte1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carte1MouseClicked
        // TODO add your handling code here:
        
        if (i == 0){
            t1[i]="a";
            i++;
        }
        else{
        if(t1[i-1]=="a"){
            carte1.setBackground(Color.black);
            carte12.setBackground(Color.black);
            i=0;
        }else{
        i=0;
        }
        }
        jLabel1.setText(String.valueOf(i));
    }//GEN-LAST:event_carte1MouseClicked

    private void carte1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carte1MousePressed
  
    }//GEN-LAST:event_carte1MousePressed

    private void carte12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carte12MouseClicked
        // TODO add your handling code here:
        
        if (i == 0){
            t1[i]="a";
            i++;
        }
        else{
        if(t1[i-1]=="a"){
            carte1.setBackground(Color.black);
            carte12.setBackground(Color.black);
            i=0;
        }
        else{
        i=0;
        }
        }
        jLabel1.setText(String.valueOf(i));
    }//GEN-LAST:event_carte12MouseClicked

    private void carte3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carte3MouseClicked
        // TODO add your handling code here:
        
        if (i == 0){
            t2[i]="a";
            i++;
        }
        else{
        if(t2[i-1]=="a"){
            carte9.setBackground(Color.black);
            carte3.setBackground(Color.black);
            i=0;
        }
        else{
        i=0;
        }
        }
        jLabel1.setText(String.valueOf(i));
    }//GEN-LAST:event_carte3MouseClicked

    private void carte9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carte9MouseClicked
        // TODO add your handling code here:
        if (i == 0){
            t2[i]="a";
            i++;
        }
        else{
        if(t2[i-1]=="a"){
            carte9.setBackground(Color.black);
            carte3.setBackground(Color.black);
            i=0;
        }
        else{
        i=0;
        }
        }
        jLabel1.setText(String.valueOf(i));
    }//GEN-LAST:event_carte9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jeuxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jeuxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jeuxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jeuxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jeuxFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carte1;
    private javax.swing.JLabel carte10;
    private javax.swing.JLabel carte11;
    private javax.swing.JLabel carte12;
    private javax.swing.JLabel carte2;
    private javax.swing.JLabel carte3;
    private javax.swing.JLabel carte4;
    private javax.swing.JLabel carte5;
    private javax.swing.JLabel carte6;
    private javax.swing.JLabel carte7;
    private javax.swing.JLabel carte8;
    private javax.swing.JLabel carte9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
